package edu.kaist.mrlab.annot;

public enum DBOProperty {
	// birthPlace, origin, deathPlace, residence, almaMater, employer, religion,
	// spouse, child, parent, sibling, affiliation, ceo, owner, keyPerson,
	// subsidiary, parentCompany, foundedBy, headquarter
//	birthDate, birthYear, deathDate, deathYear
	birthPlace, occupation, genre, club, starring, country, nationality, order, location, position, language, commander, owningOrganisation, kingdom, team, director, phylum, division, recordLabel, family, producer, youthClub, deathPlace, currentMember, channel, distributor, previousWork, instrument, subsequentWork, artist, writer, managerClub, education, religion, type, genus, nationalTeam, region, voice, timeZone, computingPlatform, relative, spouse, format, musicalBand, musicalArtist, ground, tenant, award, place, league, predecessor, developer, city, parent, successor, author, musicComposer, ideology, album, party, hubAirport, domain, child, headquarter, languageFamily, pastMember, leaderName, isPartOfMilitaryConflict, editing, parentCompany, officialLanguage, recordedIn, residence, industry, owner, operatingSystem, keyPerson, locatedInArea, composer, routeStart, routeEnd, colour, influencedBy, publisher, battle, capital, knownFor, basedOn, cinematography, influenced, computingMedia, computingInput, field, regionServed, license, manufacturer, foundedBy, manager, governmentType, operatedBy, associatedAct, creativeDirector, commandStructure, operator, targetAirport, notableWork, garrison, vicePresident, endingTheme, product, species, related, veneratedIn, subsidiary, series, currency, season, openingTheme, usedInWar, populationPlace, service, designer, assembly, literaryGenre, gameEngine, programmingLanguage, restingPlace, bodyStyle, deathCause, creator, militaryBranch, architect, source, president, mainInterest, doctoralAdvisor, doctoralStudent, anthem, canonizedBy, executiveProducer, beatifiedBy, department, sourcePlace, sourceMountain, alliance, notableIdea, crosses, largestCity, archipelago, philosophicalSchool, usingCountry, engine, musicSubgenre, significantBuilding, maintainedBy, nonFictionSubject, parentMountainPeak, narrator, era, almaMater, musicFusionGenre, derivative, hometown, translator, designCompany, mediaType, leftTributary, ethnicity, chairperson, formerTeam, rightTributary, opponent, launchSite, arrondissement, variantOf, contractor, sportGoverningBody, outflow, firstAscentPerson, gender, equipment, citizenship, lastAppearance, illustrator, artery, rocketFunction, mouthCountry, leader, sourceRegion, sourceCountry, category, parentOrganisation, mouthRegion, origin, openingFilm, march, majorIsland, inflow, sourceConfluence, selection, previousMission, mainOrgan, binomial, nextMission, musicians, musicBy, coverArtist, nerve, lyrics, closingFilm, chiefEditor, significantProject, resolution, hasVariant, engineer, countryOrigin, builder, vein, lymph, mayor, sisterNewspaper, lastFlight, firstFlight, provost, launchPad, academicDiscipline, namedAfter, canton, sourceConfluenceRegion, sourceConfluenceCountry, precursor, partner, island, board, significantDesign, managingEditor, locationCountry, bodyDiscovered
//	birthPlace
}
